#!/bin/bash
#
#
#
#
clear
echo "___________________________________________________"
echo "|         Atualizador da IDE do Bin S.O           |"
echo "|                                                 |"
echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
echo "|_________________________________________________|"
echo -e
echo -e
echo "Atualizando a IDE do Bin S.O...         [ Aguarde ]"
echo -e
echo -e
sleep 4
wget https://github.com/felipelunkes/binIDE/blob/master/a++
wget https://github.com/felipelunkes/binIDE/blob/master/montar
wget https://github.com/felipelunkes/binIDE/blob/master/instalar
wget https://github.com/felipelunkes/binIDE/blob/master/instalarapp
wget https://github.com/felipelunkes/binIDE/blob/master/info
wget https://github.com/felipelunkes/binIDE/blob/master/status
wget https://github.com/felipelunkes/binIDE/blob/master/configure
wget https://github.com/felipelunkes/binIDE/blob/master/sisinfo
wget https://github.com/felipelunkes/binIDE/blob/master/suite
wget https://github.com/felipelunkes/binIDE/blob/master/imagem
wget https://github.com/felipelunkes/binIDE/blob/master/util
wget https://github.com/felipelunkes/binIDE/blob/master/atualizar
clear
echo "___________________________________________________"
echo "|         Atualizador da IDE do Bin S.O           |"
echo "|                                                 |"
echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
echo "|_________________________________________________|"
echo -e
echo -e
echo "Atualizando os arquivos de instalação do Bin S.O..."
echo -e
echo -e
sleep 4
wget https://github.com/felipelunkes/binIDE/blob/master/binkernel
wget https://github.com/felipelunkes/binIDE/blob/master/binloader
wget https://github.com/felipelunkes/binIDE/blob/master/ajuda
wget https://github.com/felipelunkes/binIDE/blob/master/sobre
wget https://github.com/felipelunkes/binIDE/blob/master/mem
wget https://github.com/felipelunkes/binIDE/blob/master/processador
wget https://github.com/felipelunkes/binIDE/blob/master/ver
wget https://github.com/felipelunkes/binIDE/blob/master/binmouse
wget https://github.com/felipelunkes/binIDE/blob/master/clear
wget https://github.com/felipelunkes/binIDE/blob/master/video
wget https://github.com/felipelunkes/binIDE/blob/master/som
wget https://github.com/felipelunkes/binIDE/blob/master/echo
wget https://github.com/felipelunkes/binIDE/blob/master/desligar
wget https://github.com/felipelunkes/binIDE/blob/master/reiniciar
wget https://github.com/felipelunkes/binIDE/blob/master/reg
echo -e
echo -e 
echo "Atualização completa."
echo -e
echo -e





