#!/bin/bash
#
#
#
# Script para a criação de imagens virtuais do Bin S.O em um disco rígido que não pode ser utilizado
# ou que já possua um sistema operacional instalado.
#
#
#
#

EMULAR(){
	
	clear
    echo "_________________________________________________"
	echo "|  Dev Suite Gerenciador de Imagens do Bin S.O  |"
	echo "|                                               |"
	echo "| Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_______________________________________________|"
	echo -e
	echo -e
	echo "Iniciando máquina virtual com a imagem virtual do Bin S.O..."
	echo -e
	echo -e
	qemu-system-i386 -hda imagens/bin.img -m 123 -soundhw pcspk -no-kvm
	echo -e
	echo -e
	echo "_________________________________________________"
	echo "|  Dev Suite Gerenciador de Imagens do Bin S.O  |"
	echo "|                                               |"
	echo "| Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_______________________________________________|"
    echo "|                                               |"
    echo "| Fim da Execução em Máquina Virtual do Bin S.O |"
    echo "|                                               |"
    echo "|_______________________________________________|"

}

CRIARIMAGEM(){
	
	clear
	echo "_________________________________________________"
	echo "|  Dev Suite Gerenciador de Imagens do Bin S.O  |"
	echo "|                                               |"
	echo "| Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_______________________________________________|"
	echo -e
	echo -e
	echo "Criando imagem com o Sistema Operacional Bin S.O..."
	echo -e
	echo -e
	sleep 3
	mkdir imagens
	dd if=/dev/zero of=imagens/bin.img count=1440 bs=1k
	echo -e
	echo -e
	./instalar imagens/bin.img $PADRAOSISTEMA
	cp imagens/bin.img imagens/bin.iso
	cp imagens/bin.img imagens/bin.flp
	cp imagens/bin.img imagens/bin.felipe
	echo -e
	echo "Operação finalizada."
	echo -e
	if [ -e imagens/bin.img ]; then
    echo "A imagem do sistema está localizada em ./imagens/bin.img"
    else
    echo "Erro ao criar a imagem do sistema. Algum erro desconhecido ocorreu."
    fi
	echo -e
	echo -e
	
}

if test "`whoami`" != "root" ; then
    clear
   	echo "_________________________________________________"
	echo "|  Dev Suite Gerenciador de Imagens do Bin S.O  |"
	echo "|                                               |"
	echo "| Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_______________________________________________|"
	echo -e
	echo -e
	echo "Aviso: Voce nao executou o Bin S.O Dev Suite Criador de Imagens como root."
	echo -e
	echo "O processo nao pode continuar caso o usuario nao seja root."
	echo -e
	echo "Usuario atual: $USER"
	echo -e
	echo "Aviso: Caso queira continuar, especifique corretamente o dispositivo de teste"
	echo "em que o sistema e seus aplicativos serão instalados."
	echo -e
	echo "O dispositivo será formatado com BinFS e não poderá ser acessado no Linux"
	echo "antes de ser formatado com um sistema de arquivos suportado por ele."
	echo -e
	echo "O dispositivo sera formatado e os dados nao salvos serao perdidos."
	echo -e
	exit
fi

export FORMA=$1
export PADRAOSISTEMA="binloader binkernel sobre video echo ajuda reiniciar reg clear desligar processador binmouse ver mem som"

case $FORMA in

instalar) CRIARIMAGEM ;;
emular) EMULAR ;;
emu) EMULAR ;;
inst) CRIARIMAGEM ;;

esac

