#!/bin/bash
#
#
#
#
#  ___________________________________________________
#  | Dev Suite Gerenciador de Instalações do Bin S.O |
#  |                                                 |
#  |   Copyright (C) 2013 Felipe Miguel Nery Lunkes  |
#  |_________________________________________________|
#
#
#
# Programa-Rotina para a instalação de Softwares para Bin S.O
#
#
#
# O padrão dos aplicativos do sistema operacional Bin S.O e os componentes.
#
#
#
#
#
#

ERRODEV(){
	
	clear
	echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "| Erro ao procurar dispositivo para a instalação  |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "O dispositivo '$DEV' não pode ser utilizado para uma instalação"
	echo "regular do Bin S.O."
	echo -e
	echo "Este dispositivo é incompatível, está desconectado do computador,"
	echo "está em uso por outro processo ou está temporariamente indisponível"
	echo "para o uso com este aplicativo da 'Dev Suite do Bin S.O para Linux'."
    echo -e
    echo "Dev Suite do Bin S.O para Linux - Versão 1.0"
    echo -e
    echo "Copyright (C) 2013 Felipe Miguel Nery Lunkes"
    echo -e
    echo -e
    echo "Para saber mais sobre os requisitos do dispositivo, insira instalarapp requisitos."
    echo -e
    echo -e
    exit
    
}

ERRODEVEMULAR(){
	
	clear
	echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|    Ferramenta de Execução Virtual do Bin S.O    |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "O dispositivo '$DEV' não pode ser utilizado para iniciar uma"
	echo "máquina virtual para executar o Bin S.O."
	echo -e
	echo "Este dispositivo é incompatível, está desconectado do computador,"
	echo "está em uso por outro processo ou está temporariamente indisponível"
	echo "para o uso com este aplicativo da 'Dev Suite do Bin S.O para Linux'."
    echo -e
    echo "Dev Suite do Bin S.O para Linux - Versão 1.0"
    echo -e
    echo "Copyright (C) 2013 Felipe Miguel Nery Lunkes"
    echo -e
    echo -e
    echo "Para saber mais sobre os requisitos do dispositivo, insira instalarapp requisitos."
    echo -e
    echo -e
    exit
    
}



Emular(){
	
	clear
	echo -e
	if [ -e $DEV ]; then
CONTINUAREMULAR
    else
    ERRODEVEMULAR
    fi
    
}
    
CONTINUAREMULAR(){
	
	clear
	echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|    Ferramenta de Execução Virtual do Bin S.O    |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Verificando dispositivo $DEV e os arquivos do sistema...   [PRONTO]"
	sleep 3
	echo -e
	echo "Iniciando máquina virtual x86..."
	echo -e
	sleep 1
	echo "Iniciando o Bin S.O sobre a máquina virtual..."       
	echo -e
	sudo qemu-system-i386 -hda $DEV -m 5 -soundhw pcspk -no-kvm -cpu athlon
	echo -e
	echo -e
	echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|       Fim desta suíte de testes do Bin S.O      |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	exit
	
}

VERIFICAR(){
	
	if [ -e binloader ]; then
	echo "Arquivo BINLOADER do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e binkernel ]; then
	echo "Arquivo BINKERNEL do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e ajuda ]; then
	echo "Arquivo AJUDA do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e sobre ]; then
	echo "Arquivo SOBRE do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e ver ]; then
	echo "Arquivo VER do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e mem ]; then
	echo "Arquivo MEM do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e processador ]; then
	echo "Arquivo PROCESSADOR do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e video ]; then
	echo "Arquivo VIDEO do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e echo ]; then
	echo "Arquivo ECHO do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e clear ]; then
	echo "Arquivo CLEAR do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e som ]; then
	echo "Arquivo SOM do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e desligar ]; then
	echo "Arquivo DESLIGAR do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e reiniciar ]; then
	echo "Arquivo REINICIAR do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e reg ]; then
	echo "Arquivo REG do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e binmouse ]; then
	echo "Arquivo BINMOUSE do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	if [ -e instalar ]; then
	echo "Aplicativo de Instalação do Bin S.O encontrado"
	else
	ERROARQUIVO
	fi
	
	$APPPROC
	
}
	
	
	
	
InstalarEmular(){
	
	clear
	echo -e
	if [ -e $DEV ]; then
VERIFICAR
    else
    ERRODEV
    fi
    
}

CONTINUARINSTALAREMULAR(){
	clear
	echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|   Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Dev Suite do Bin S.O sendo executada por $USER ."
	echo -e
	echo -e
	echo "Aguarde. Realizando as operações necessárias a instalação..."
	echo -e
	echo -e
	sleep 3
	sudo mkdosfs $DEV -I >> /dev/null
	clear
	echo -e
	echo -e
    echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|   Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Instalando os Softwares adicionais selecionados no Disco $DEV..."
	echo -e
	echo -e
	echo "Dispositivo para a instalacao: $DEV"
	echo -e
	echo "Softwares: $SOFTWARE2 $SOFTWARE3 $SOFTWARE4 $SOFTWARE5 $SOFTWARE6 $SOFTWARE7 $SOFTWARE8 $SOFTWARE9"
	sleep 2
	echo -e
	echo -e
	./instalar $DEV $PADRAOSISTEMA	$SOFTWARE1	$SOFTWARE2	$SOFTWARE3	$SOFTWARE4	
	echo -e
	echo -e
	CONTINUAREMULAR
	exit
	
}

Requisitos(){
	
	clear
	echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|   Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Para uma instalação regular do Bin S.O em um dispositivo de armazenamento,"
	echo "alguns requisitos devem ser respeitados."
	echo -e
	echo "O dispositivo deve apresentar no mínimo 1 MB de memória disponível (livre)"
	echo "para a gravação do sistema e de seus aplicativos nativos/do usuário."
	echo -e
	echo "O dispositivo deverá ser uma mídia rígida (como um HD ou um Pen Drive apenas)."
	echo -e
	echo -e
	echo "Dev Suite Gerenciador de Instalaçãoes do Bin S.O"
	echo -e
	echo "Copyright (C) 2013 Felipe Miguel Nery Lunkes"
	echo -e
	echo -e
	
}

Instalador(){
	clear
	echo -e
	if [ -e $DEV ]; then
VERIFICAR
    else
    ERRODEV
    fi
}

CONTINUARINSTALADOR(){
    
	clear
	echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|   Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Dev Suite do Bin S.O sendo executada por $USER ."
	echo -e
	echo -e
	echo "Aguarde. Realizando as operações necessárias a instalação..."
	echo -e
	echo -e
	sleep 5
	sudo mkdosfs $DEV -I >> /dev/null
	clear
	echo -e
	echo -e
    echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|   Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Instalando os Softwares adicionais selecionados no Disco $DEV..."
	echo -e
	echo -e
	echo "Dispositivo para a instalacao: $DEV"
	echo -e
	echo "Softwares: $SOFTWARE2 $SOFTWARE3 $SOFTWARE4 $SOFTWARE5 $SOFTWARE6 $SOFTWARE7 $SOFTWARE8 $SOFTWARE9"
	sleep 2
	echo -e
	echo -e
	./instalar $DEV $PADRAOSISTEMA	$SOFTWARE1	$SOFTWARE2	$SOFTWARE3	$SOFTWARE4	
	echo -e
	echo -e
	echo
}

CVER(){
	
#
# Exibe a versão no estilo C.
#

echo "Dev Suite Gerenciador de Instalações do Bin S.O versão 1.0"
echo "Desenvolvido exclusivamente para Linux"
echo "Copyright (C) 2013 Felipe Miguel Nery Lunkes"
exit

}

INFORMACOES(){
	
	clear
	echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|   Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Tipo de Sistema Operacional: $TIPO"
	echo "Versão do Sistema Operacional: $VERSAOSIS"
	echo "Usuário: $USUARIO"
	echo "Arquitetura do Sistema Operacional: $ARQUITETURA"
	echo "Conjurado pelo Shell: $SHELL"
	echo -e
	echo -e
	echo "Copyright (C) 2013 Felipe Miguel Nery Lunkes"
	echo -e
	echo -e

}
	

ver(){
	
	clear
	echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|   Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Instalador do Sistema e ferramentas de teste do Bin S.O sobre o Linux"
	echo -e
	echo -e
	echo "Versao: $APPVER"
	echo -e
	echo -e
	echo "Copyright (C) 2013 Felipe Miguel Nery Lunkes"
	echo -e
	echo -e
	echo "Todos os direitos reservados."
	echo -e
	echo -e
	
}

if test "`whoami`" != "root" ; then

    clear
    echo "___________________________________________________"
	echo "| Dev Suite Gerenciador de Instalações do Bin S.O |"
	echo "|                                                 |"
	echo "|   Copyright (C) 2013 Felipe Miguel Nery Lunkes  |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Aviso: Voce nao executou o Bin S.O Dev Suite como root."
	echo -e
	echo "O processo nao pode continuar caso o usuario nao seja root."
	echo -e
	echo "Aviso: Caso queira continuar, especifique corretamente o dispositivo de teste"
	echo "em que o sistema e seus aplicativos serão instalados."
	echo -e
	echo "O dispositivo será formatado com BinFS e não poderá ser acessado no Linux"
	echo "antes de ser formatado com um sistema de arquivos suportado por ele."
	echo -e
	echo "O dispositivo sera formatado e os dados nao salvos serao perdidos."
	echo -e
	
	exit
fi

export DEV=$2
export DISPOSITIVO=$2
export SOFTWARE2=$3
export SOFTWARE3=$4
export SOFTWARE4=$5
export SOFTWARE5=$6
export SOFTWARE6=$7
export SOFTWARE7=$8
export SOFTWARE8=$9
export APPVER="1.0"
export AUTOR="Felipe Miguel Nery Lunkes"
export APPNOME="Dev Suite Gerenciador de Instalações para Bin S.O"
export DATA=0x1000
export SIS_AREA=0x1000:0
export PADRAOSISTEMA="binloader binkernel sobre video echo ajuda reiniciar reg clear desligar processador binmouse ver mem som"
export SHELL=$SHELL
export Instalador="Instalador de Programas do Bin S.O"
export VER="1.0"
export TIPO=$OSTYPE
export USUARIO=$USER
export VERSAOSIS=$(uname -r)
export ARQUITETURA=$MACHTYPE


case $1 in

instalar) export APPPROC=CONTINUARINSTALADOR; Instalador ; exit ;;
instalaremular) export APPPROC=CONTINUARINSTALAREMULAR; InstalarEmular; exit;;
ver) ver; exit;;
emular) Emular; exit;;
requisitos) Requisitos ;;
--v) CVER ;;
--info) INFORMACOES ;;

esac

export DEV=$2
export SOFTWARE2=$3
export SOFTWARE3=$4
export SOFTWARE4=$5
export SOFTWARE5=$6
export SOFTWARE6=$7
export SOFTWARE7=$8
export SOFTWARE8=$9
export APPVER="1.0"
export AUTOR="Felipe Miguel Nery Lunkes"
export APPNOME="Dev Suite Gerenciador de Instalações para Bin S.O"
export DATA=0x1000
export SIS_AREA=0x1000:0
export PADRAOSISTEMA="binloader binkernel sobre video echo ajuda reiniciar reg clear desligar processador binmouse ver mem som"
export SHELL=/bin/bash
export Instalador="Instalador de Programas do Bin S.O"
export VER="1.0"
export NOME=$0

