#!/bin/bash
#
#
#
#
#

SIS(){
	
clear
echo "___________________________________________________"
echo "|       Dev Suite SDK do Bin S.O para Linux       |"
echo "|                                                 |"
echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
echo "|_________________________________________________|"
echo "|                                                 |"
echo "|     Sobre seu sistema operacional instalado     |"
echo "|                                                 |"
echo "|                Versão 1.0 Linux                 |"
echo "|_________________________________________________|"
echo -e
echo -e
echo "Informacoes do Sistema Operacional ambiente de instalacao"
echo -e
echo "Sistema Operacional: GNU/LINUX $VERSAOLINUX"
echo "Usuario: $USER"
echo "Arquitetura do Sistema: $MACHTYPE"
echo "Tipo de Sistema: $OSTYPE"
echo -e
echo "Data e hora: $DATA"
echo "Nome de HOST: $NOMEHOST"
echo -e
echo -e
    
}    

export VERSAOLINUX=$(uname -r)
export DATA=$(date)
export NOMEHOST=$(hostname)

SIS
