#!/bin/bash
#
#
#
# O dispositivo usado para a instalação deve ser especificado em $1
#
# O programa emulador de máquina virtual deve ser especificado em $2
#
# Os parametros de memoria devem ser especificados em $3
#
# Os parametros de som devem ser especificados em $4
#
#

Emular(){
	
	clear
	sudo qemu-system-$maquinavirtual -hda $dispositivo -m $memoria -soundhw $drvsom -no-kvm
}

sem(){
	
	Emular
	
}

SAIR(){
	
	exit
	exit
	
}

TESTEMEMORIA(){
	
	case $memoria in
	1) Emular ;;
	2) Emular ;;
	3) Emular ;;
	4) Emular ;;
	5) Emular ;;
	6) clear;
	   echo -e;
	   echo -e
	   echo "O Bin S.O utiliza apenas 1 MB de memória RAM para seu funcionamento.";
	   echo -e;
	   echo -e;
	   echo "Você declarou mais de 5 MB para a Máquina Virtual.";
	   echo -e;
	   echo -e;
	   echo "Perda de desempenho por parte do Sistema Operacional hospedeiro detectada.";
	   echo -e;
	   echo -e;
	   echo "Utilize um valor de 1 a 5 para evitar perdas de desempenho.";
	   echo -e;
	   echo -e;
	   exit ;;
	   esac
	   
		  
   }
	   
determinepadrao(){
	
	export applista="binloader binkernel sobre video echo ajuda reiniciar reg clear desligar processador binmouse ver mem som"
    
    ./instalar $dispositivo $applista
    
    case $drvsom in
	pcspk) TESTEMEMORIA ;;
	*) clear;
	   echo -e;
	   echo -e;
	   echo "Aviso!";
	   echo -e;
	   echo -e;
	   echo "Este driver de som nao esta disponivel e nao pode ser usado pelo emulador.";
	   echo -e;
	   echo "O sistema de som desejado nao é compatível com o Bin S.O no momento.";
	   echo -e;
	   exit ;;
	   esac

}

determineteste(){
	
	export applista="binloader binkernel sobre ver clear reiniciar reg processador"
	
	./instalar $dispositivo $applista
	
	 case $drvsom in
	pcspk) TESTEMEMORIA ;;
	*) clear;
	   echo -e;
	   echo -e;
	   echo "Aviso!";
	   echo -e;
	   echo -e;
	   echo "Este driver de som nao esta disponivel e nao pode ser usado pelo emulador.";
	   echo -e;
	   echo "O sistema de som desejado nao é compatível com o Bin S.O no momento.";
	   echo -e;
	   exit ;;
	   esac
	   
}
TESTE(){
	
	
	case $app in
	padrao) determinepadrao ;;
	teste) determineteste ;;
	seminstalar) sem ;;
	*) clear;
	   echo -e;
	   echo -e;
	   echo "Aviso!";
	   echo -e;
	   echo -e;
	   echo "Instalador do Sistema Operacional Bin S.O";
	   echo -e;
	   echo "Parametro para a instalacao do sistema invalido" ;
	   echo -e;
	   echo "Parametro inserido pelo usuario no Dev Suite: $app";
	   echo -e;
	   echo -e;
	   echo "Os parametros validos sao: padrao, teste, seminstalar.";
	   echo -e;
	   echo -e;
	   exit ;;
	   esac
	   
	   
}

pacotes(){
	clear
	echo -e
	echo -e
	echo "Dev Suite do Bin S.O para Linux"
	echo "---*---*---*---*---*---*---*---"
	echo -e
	echo -e
	echo "Procurando, realizando download e instalando Qemu..."
	echo -e
	sudo $PACOTES qemu
	echo -e
	echo -e
	echo "Instalando Dev Suite Nasm (Nasm assembler para Bin S.O)..."
	echo -e
	sudo cp nasm/nasm /usr/bin
	echo -e
	echo -e
	echo "Pronto. Instalacao de aplicativos concluida."
	echo -e
	echo -e
	echo "Pressione ENTER para continuar..."
	read ENTER
	ajuda
	
}

ver(){
	
	clear
	echo -e
	echo -e
	echo "Dev Suite do Bin S.O para Linux"
	echo "---*---*---*---*---*---*---*---"
	echo -e
	echo -e
	echo "Instalador do Sistema e ferramentas de teste do Bin S.O sobre o Linux"
	echo -e
	echo -e
	echo "Versao: $APPVER"
	echo -e
	echo -e
	echo "Copyright (C) 2013 Felipe Miguel Nery Lunkes"
	echo -e
	echo -e
	echo "Todos os direitos reservados."
	echo -e
	echo -e
	
}

ajudadev(){
	
	clear
	echo -e
	echo "Suite de Instalação do Bin S.O sobre o Linux"
	echo -e 
	echo -e
    echo "O primeiro parametro passado a Dev Suite deve ser o dispositivo de armazenamento"
    echo "físico."
    echo -e
    echo -e
    echo "O dispositivo deve estar conectado ao computador no momento da execucao."
    echo -e
    echo "O dispositivo sera formatado com BinFS e todos os ados nao salvos serao"
    echo "perdidos com a formatacao."
    echo -e
    echo -e
    echo "Como declarar um dispositivo:"
    echo -e
    echo "sudo ./suite /dev/sdg"
    echo -e
    echo "O dispositivo do exemplo foi tomado como /dev/sdg"
    echo -e
    echo -e
    
}
ajuda(){
	
	clear
	echo -e
	echo "Suite de Instalação do Bin S.O sobre o Linux"
	echo -e
	echo -e
	echo "# O dispositivo usado para a instalação deve ser especificado no argumento 1."
	echo "# O dispositivo usado para executar o sistema em maquina virtual x86 deve ser"
	echo "# especificado no argumento 1."
    echo "# A arquitetura do qemu deve ser especificado no argumento 2.(x86 ou x64 apenas)"
    echo "# Os parametros de memoria devem ser especificados no argumento 3."
    echo "# Os parametros de som devem ser especificados no argumento 4."
    echo "# Os parametros de instalacao do sistema devem ser especificados no argumento 5."
    echo -e
    echo "Caso o argumento 1 seja declarado como 'ajuda', este menu será aberto."
    echo "Caso o argumento 1 seja declarado como 'ajudadev' a ajuda de dispositivo sera"
    echo "aberta."
    echo -e
    echo "Caso o argumento 1 seja declarado como 'ver', a versao sera exibida."
    echo -e
    echo "Sistema Operacional: GNU/LINUX $VERSAOKERNEL"
    echo -e
    echo "Data: $DATA"
    echo -e
    echo "Executando em arquitetura: $Arquitetura"
    echo -e
    
}


if test "`whoami`" != "root" ; then
    clear
    echo -e
    echo -e
    echo "Dev Suite Instalador de Apps para Bin S.O"
    echo "---*---*---*---*---*---*---*---*---*---*---"
    echo -e
    echo -e
	echo "Aviso: Voce nao executou o Bin S.O Dev Suite Instalador de Apps como root."
	echo -e
	echo "O processo nao pode continuar caso o usuario nao seja root."
	echo -e
	echo "Usuario atual: $USER"
	echo -e
	echo "Aviso: Caso queira continuar, especifique corretamente o dispositivo de teste"
	echo "em que o sistema e seus aplicativos serão instalados."
	echo -e
	echo "O dispositivo será formatado com BinFS e não poderá ser acessado no Linux"
	echo "antes de ser formatado com um sistema de arquivos suportado por ele."
	echo -e
	echo "O dispositivo sera formatado e os dados nao salvos serao perdidos."
	echo -e
	exit
fi

#
# Aqui estarão as variáveis utilizadas pelo sistema
#
# Copyright (C) 2013 Felipe Miguel Nery Lunkes
#

export dispositivo=$1
export maquinavirtual="i386"
export memoria=$3
export drvsom=$4
export app=$5
export Sistema=$OSTYPE
export Arquitetura=$HOSTTYPE
export ArqMaq=$MACHTYPE
export AUTOR="Felipe Miguel Nery Lunkes"
export VER="1.0"
export COPYRIGHT="Copyright (C) 2013 Felipe Miguel Nery Lunkes"
export DATA=$(date)
export VERSAOKERNEL=$(uname -r)
export RETPROC=$(cat /proc/version)
export PROCESSADOR=$(cat /proc/cpuinfo)
export MEM=$(cat /proc/meminfo)
export APPVER="1.0"
export PACOTES="apt-get install"
export DIRETIVAS"install"

case $1 in

ajuda) ajuda ; exit ;;
ajudadev) ajudadev; exit;;
ver) ver; exit;;
pacotes) pacotes; exit;;
ajudapacotes) ajudapacotes; exit;;

esac


TESTE
