#!/bin/bash
#
#
#
#
# Gerenciador para a instalação de utilidades necessárias para a IDE
#
#
#
#

GEANY(){
	
	clear
	echo "___________________________________________________"
	echo "|   Instalador de Utilidades da IDE do Bin S.O    |"
	echo "|                                                 |"
	echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Instalando editor de arquivos fonte Geany..."
	echo -e
	echo -e
	$PACOTES geany
	echo -e
	echo -e
	echo "Pronto."
	echo -e
	echo -e
	exit
	
}

QEMU(){
	
	clear
	echo "___________________________________________________"
	echo "|   Instalador de Utilidades da IDE do Bin S.O    |"
	echo "|                                                 |"
	echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Instalando gerenciador de máquinas virtuais QEMU..."
	echo -e
	echo -e
	$PACOTES qemu
	echo -e
	echo -e
	echo "Pronto."
	echo -e
	echo -e
	exit
	
}

NASM(){
	
	clear
	echo "___________________________________________________"
	echo "|   Instalador de Utilidades da IDE do Bin S.O    |"
	echo "|                                                 |"
	echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Instalando compilador/montador Nano Dev Suite..."
	echo -e
	echo -e
	cp nasm/nasm /usr/bin
	echo -e
	echo -e
	echo "Pronto."
	echo -e
	echo -e
	exit
	
}

NANO(){
	
	clear
	echo "___________________________________________________"
	echo "|   Instalador de Utilidades da IDE do Bin S.O    |"
	echo "|                                                 |"
	echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Instalando editor GNU Nano..."
	echo -e
	echo -e
	$PACOTES nano
	echo -e
	echo -e
	echo "Pronto."
	echo -e
	echo -e
	exit
	
}

SEMPAR(){
	
	clear
	echo "___________________________________________________"
	echo "|   Instalador de Utilidades da IDE do Bin S.O    |"
	echo "|                                                 |"
	echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "O parâmetro passado é inválido."
	echo -e
	echo -e
	
}

VER(){
	
	clear
	echo "___________________________________________________"
	echo "|   Instalador de Utilidades da IDE do Bin S.O    |"
	echo "|                                                 |"
	echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "IDE do Bin S.O para Linux Versão 1.0"
	echo "---*---*---*---*---*---*---*---*---*---"
	echo -e
	echo -e
	echo "Este programa instala os programas necessários para que"
	echo "a IDE funcione corretamente."
	echo -e
	echo -e
	exit
	
}
if test "`whoami`" != "root" ; then

    clear
    echo "___________________________________________________"
	echo "|   Instalador de Utilidades da IDE do Bin S.O    |"
	echo "|                                                 |"
	echo "|  Copyright (C) 2013 Felipe Miguel Nery Lunkes   |"
	echo "|_________________________________________________|"
	echo -e
	echo -e
	echo "Aviso: Voce nao executou o Bin S.O Dev Suite compilador de aplicativos como root."
	echo -e
	echo "O processo nao pode continuar caso o usuario nao seja root."
	echo -e
	echo -e
	
	exit
fi

export FUNCAO=$1
export PACOTES="apt-get install -y"

case $FUNCAO in

geany) GEANY ;;
qemu) QEMU ;;
nano) NANO ;;
ver) VER ;;
nasm) NASM ;;
*) SEMPAR ;;

esac

